baseURL = "https://wanderland24.github.io"
title = "WanderLand"
author = "username"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.jpg"
    alt = "Tella Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-15"

  [params.site]
    name = "WanderLand"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true
  
  [params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "http://baidu.com"
    link_text = "Check other homepages"

[menu]

  [[menu.main]]
    name = "DESTINATION"
    url = "/destination/"
    weight = 1

  [[menu.main]]
    name = "SERVICE"
    url = "/service/"
    weight = 2

  [[menu.main]]
    name = "CONTACT US!"
    url = "/contact/"
    weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1
